apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhnmrt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhnmrt
  template:
    metadata:
      labels:
        app: dhnmrt
    spec:
      containers:
      - image: okteto.dev/dhnmrt:latest
        name: dhnmrt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e92d7edf-198d-420d-a882-4e819ae0c6d3"
        - name: Vless_Path
          value: "/vl55599"
        - name: Vmess_UUID
          value: "e92d7edf-198d-420d-a882-4e819ae0c6d3"
        - name: Vmess_Path
          value: "/vm66688"
        - name: Share_Path
          value: "/v2link"
